# Generated by Django 4.2.23 on 2025-08-01 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='scheduled_for',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
